# numpy를 사용하여 이미지 저장 시 효율 비교

In [1]:
import numpy as np
from PIL import Image

In [3]:
# 이미지 불러오기
img=Image.open("../data/cat.png").convert('L') # 그레이 스케일 변환
print(img)

<PIL.Image.Image image mode=L size=310x162 at 0x111B7EE10>


In [4]:
img_array=np.array(img)
print(img_array)

[[222 222 222 ... 169 169 169]
 [223 223 223 ... 168 168 168]
 [223 223 223 ... 165 165 165]
 ...
 [219 219 222 ... 235 234 234]
 [221 222 224 ... 236 236 235]
 [221 222 224 ... 236 236 235]]


In [5]:
np.save('../data/pil_image.npy',img_array)

In [6]:
image_array1=np.load('../data/pil_image.npy')
print(image_array1)

[[222 222 222 ... 169 169 169]
 [223 223 223 ... 168 168 168]
 [223 223 223 ... 165 165 165]
 ...
 [219 219 222 ... 235 234 234]
 [221 222 224 ... 236 236 235]
 [221 222 224 ... 236 236 235]]


In [8]:
# 다시 PIL 이미지로 변환
img=Image.fromarray(np.uint8(image_array1))
img.save('../data/img_numpy.png')

In [15]:
import os
np_save_size=os.path.getsize('../data/pil_image.npy')
print(np_save_size,"bytes") #byte 단위임

50348 bytes


In [16]:
pil_save_size=os.path.getsize('../data/img_numpy.png')
print(pil_save_size,"bytes")

26813 bytes
