# Numpy

- C언어로 개발된 파이썬에서 과학적 계산을 위한 핵심 라이브러리. 다차원 배열 객체와 배열과 함께 작동하는 도구들을 제공한다.
하지만 고수준의 데이터 분석기능을 제공하지는 않기 때문에 Numpy 배열과 함께 Pandas와 같은 도구를 함께 사용한다. 

## 1차원 `value` --> 2차원 `vector` --> 3차원

In [2]:
import numpy as np #as : aliasing

In [5]:
arr = np.array([1,2,3,4])
print(arr)
print(type(arr))

[1 2 3 4]
<class 'numpy.ndarray'>


In [8]:
# zeros, ones, empty 를 사용해서 배열을 생성
car= np.zeros((3,3))
print(car)
print(type(car))

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
<class 'numpy.ndarray'>


In [10]:
np.ones((2,2))

array([[1., 1.],
       [1., 1.]])

In [12]:
np.empty((4,4))

array([[2.45252764e-316, 0.00000000e+000, 2.41907520e-312,
        2.37663529e-312],
       [2.22809558e-312, 2.46151512e-312, 6.79038654e-313,
        2.35541533e-312],
       [2.46151512e-312, 6.79038654e-313, 2.35541533e-312,
        6.79038654e-313],
       [2.14321575e-312, 2.22809558e-312, 2.14321575e-312,
        6.90773290e-310]])

In [15]:
# 특정 범위의 변수를 생성할 떄 arange()를 사용한다.
print(np.arange(10))
print(np.arange(1,10))
print(np.arange(1,10,2))

[0 1 2 3 4 5 6 7 8 9]
[1 2 3 4 5 6 7 8 9]
[1 3 5 7 9]


In [17]:
# ndarray 배열의 모양, 차수, 데이터 타입 확인해보기

arr= np.array([[1,2,3],[4,5,6]])
print(arr)

[[1 2 3]
 [4 5 6]]


In [18]:
arr.ndim #차원 확인

2

In [19]:
arr.shape

(2, 3)

In [20]:
print(arr.dtype) #데이터 타입

int64


In [23]:
# ndarray 배열의 타입 변환
arr_int= np.array([1,2,3,4])
print(arr_int.dtype)
arr_float=arr_int.astype(np.float64) # astype() : 원하는 형태로 datatype을 변경
print(arr_float.dtype)

int64
float64


In [25]:
arr_str = np.array(['1','2','3'])
print(arr_str.dtype)
arr_int=arr_str.astype(np.int64)
print(arr_int.dtype)

<U1
int64


In [27]:
# 배열의 연산

arr1=np.array([[1,2],[3,4]])
arr2=np.array([[5,6],[7,8]])

print(arr1+arr2)
print(arr1-arr2)
print(arr1*arr2)


[[ 6  8]
 [10 12]]
[[-4 -4]
 [-4 -4]]
[[ 5 12]
 [21 32]]


In [29]:
# method로 사용법 (일반적으로 method 사용을 권장하지만 numpy는 연산자 사용을 많이 함)
print(np.add(arr1,arr2))
print(np.multiply(arr1,arr2))

[[ 6  8]
 [10 12]]
[[ 5 12]
 [21 32]]


In [32]:
#ndarray 배열 슬라이싱 하기
arr=np.array([[1,2,3],
              [4,5,6],
              [7,8,9]])

In [35]:
arr_1=arr[:2,1:3]
print(arr_1)

[[2 3]
 [5 6]]


In [38]:
arr=np.array([[1,2,3],[4,5,6],[7,8,9]])
arr[0,2]

3

In [40]:
arr=np.array([[1,2,3],[4,5,6]])
idx=arr>3
print(idx)

[[False False False]
 [ True  True  True]]


In [41]:
arr[idx]

array([4, 5, 6])

In [42]:
!pwd

/content


In [47]:
redwine=np.loadtxt(fname='/content/drive/MyDrive/MS/src/winequality-red.csv',delimiter=';',skiprows=1) 

In [48]:
print(redwine)

[[ 7.4    0.7    0.    ...  0.56   9.4    5.   ]
 [ 7.8    0.88   0.    ...  0.68   9.8    5.   ]
 [ 7.8    0.76   0.04  ...  0.65   9.8    5.   ]
 ...
 [ 6.3    0.51   0.13  ...  0.75  11.     6.   ]
 [ 5.9    0.645  0.12  ...  0.71  10.2    5.   ]
 [ 6.     0.31   0.47  ...  0.66  11.     6.   ]]


In [51]:
# 기초 통계 함수
# sum   합계
# mean  평균
# std   표준편차 : 데이터와 평균치가 서로 얼마나 떨어져있는가?
# var   분산(std의 제곱) : 데이터의 차이가 작아서 안 보일때
# min   최솟값
# max   최댓값

print(redwine.sum()) #전체 데이터의 합계
print(redwine.sum(axis=0)) #axis=0 : 세로축의 합
print(redwine.mean(axis=0))

152084.78194
[13303.1       843.985     433.29     4059.55      139.859   25384.
 74302.       1593.79794  5294.47     1052.38    16666.35     9012.     ]
[ 8.31963727  0.52782051  0.27097561  2.5388055   0.08746654 15.87492183
 46.46779237  0.99674668  3.3111132   0.65814884 10.42298311  5.63602251]


In [52]:
print(redwine[:])

[[ 7.4    0.7    0.    ...  0.56   9.4    5.   ]
 [ 7.8    0.88   0.    ...  0.68   9.8    5.   ]
 [ 7.8    0.76   0.04  ...  0.65   9.8    5.   ]
 ...
 [ 6.3    0.51   0.13  ...  0.75  11.     6.   ]
 [ 5.9    0.645  0.12  ...  0.71  10.2    5.   ]
 [ 6.     0.31   0.47  ...  0.66  11.     6.   ]]


In [53]:
print(redwine.mean(axis=1)) #axis=1: 가로축의 합

[ 6.21198333 10.25456667  8.30825    ...  8.37347833  8.76795583
  7.7077075 ]


In [55]:
print(redwine[:,0].mean())

8.31963727329581


In [59]:
print(redwine.max(axis=0))
print(redwine.min(axis=0))

[ 15.9       1.58      1.       15.5       0.611    72.      289.
   1.00369   4.01      2.       14.9       8.     ]
[4.6     0.12    0.      0.9     0.012   1.      6.      0.99007 2.74
 0.33    8.4     3.     ]
